"""empty message

Revision ID: 009c7ed3f96d
Revises: 0775b9b7ade0
Create Date: 2024-09-04 22:04:31.934699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009c7ed3f96d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table("sponsor",
                    sa.Column("id", sa.Integer(), autoincrement=True),
                    sa.Column("sponsor_name", sa.String(
                        length=35), nullable=False),
                    sa.Column("sponsor_site", sa.String(), nullable=False),
                    sa.Column("sponsor_img", sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    )
    op.create_table("event",
                    sa.Column("id", sa.Integer(), autoincrement=True),
                    sa.Column("event_title", sa.String(
                        length=75), nullable=False),
                    sa.Column("event_date", sa.String(), nullable=False),
                    sa.Column("event_time", sa.String(), nullable=False),
                    sa.Column("event_location", sa.String(
                        length=120), nullable=False),
                    sa.Column("event_desc", sa.String(
                        length=500), nullable=False),
                    sa.Column("event_img", sa.String()),
                    sa.PrimaryKeyConstraint('id'),
                    )
    op.create_table('rescue',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sex', sa.Enum('Male', 'Female',
                              name='animal_sex'), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('animal_type', sa.Enum('Dog', 'Cat',
                                                     name='animal_types'), nullable=False),
                    sa.Column('animal_name', sa.String(
                        length=30), nullable=False),
                    sa.Column('can_adopt', sa.Boolean(), nullable=False),
                    sa.Column('rescue_date', sa.Date(), nullable=False),
                    sa.Column('story', sa.String(length=500), nullable=False),
                    sa.Column('breed', sa.String(length=30), nullable=False),
                    sa.Column('potty_trained', sa.Boolean(), nullable=False),
                    sa.Column('fixed', sa.Boolean(), nullable=False),
                    sa.Column('good_w_dogs', sa.Boolean(), nullable=False),
                    sa.Column('good_w_cats', sa.Boolean(), nullable=False),
                    sa.Column('good_w_kids', sa.Boolean(), nullable=False),
                    sa.Column('thumbnail_img', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('staff',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sponsor")
    op.drop_table("event")
    op.drop_table('staff')
    op.drop_table('rescue')
    # ### end Alembic commands ###
